services:
  pg:
    image: postgres:alpine
    container_name: pg_for_wg
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    # ==> file .env
    # POSTGRES_PASSWORD=
    # POSTGRES_USER=
    # POSTGRES_DB=
    volumes:
      - ./db_wg:/var/lib/postgresql/data
    ports:
      - 5433:5432

