services:
  db:
    image: postgres:alpine
    container_name: ds
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    # ==> file .env
    # POSTGRES_PASSWORD=
    # POSTGRES_USER=
    # POSTGRES_DB=
    volumes:
      - /storage/volumes/pg_db:/var/lib/postgresql/data
    #ports:
    #  - 5432:5432

  auth:
    images: reg.darksurf.local/auth:latest    
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    #ports:
    #  - "3000:3000"
